"""added stock prop in product

Revision ID: c6e8ea6cc719
Revises: 943b217a710b
Create Date: 2026-08-14 13:58:34.005175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6e8ea6cc719'
down_revision = '943b217a710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_product',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id', 'product_id')
    )
    op.create_table('order_product',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    with op.batch_alter_table('cache_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cache_locks_expiration_index'))

    op.drop_table('cache_locks')
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('failed_jobs_uuid_unique'))

    op.drop_table('failed_jobs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('jobs_queue_index'))

    op.drop_table('jobs')
    op.drop_table('password_reset_tokens')
    op.drop_table('job_batches')
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cache_expiration_index'))

    op.drop_table('cache')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('sessions_last_activity_index'))
        batch_op.drop_index(batch_op.f('sessions_user_id_index'))

    op.drop_table('sessions')
    with op.batch_alter_table('dev.users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('remember_token'))

    op.drop_table('dev.users')
    op.drop_table('migrations')
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('personal_access_tokens_expires_at_index'))
        batch_op.drop_index(batch_op.f('personal_access_tokens_token_unique'))
        batch_op.drop_index(batch_op.f('personal_access_tokens_tokenable_type_tokenable_id_index'))

    op.drop_table('personal_access_tokens')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Numeric(precision=10), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('brand', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('specs', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['product_id'])
        batch_op.drop_constraint(batch_op.f('products_user_id_foreign'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=190),
               existing_nullable=False)
        batch_op.alter_column('email_verified_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['remember_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('email_verified_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=190),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('username')
        batch_op.drop_column('profile_url')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('products_user_id_foreign'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.drop_column('stock')
        batch_op.drop_column('specs')
        batch_op.drop_column('category')
        batch_op.drop_column('brand')
        batch_op.drop_column('slug')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('image_url')
        batch_op.drop_column('category_id')
        batch_op.drop_column('product_id')

    op.create_table('personal_access_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tokenable_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('abilities', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('last_used_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('personal_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), ['tokenable_type', 'tokenable_id'], unique=False)
        batch_op.create_index(batch_op.f('personal_access_tokens_token_unique'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('personal_access_tokens_expires_at_index'), ['expires_at'], unique=False)

    op.create_table('migrations',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('migration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('batch', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dev.users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email_verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('dev.users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('remember_token'), ['remember_token'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('sessions',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('last_activity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('sessions_user_id_index'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('sessions_last_activity_index'), ['last_activity'], unique=False)

    op.create_table('cache',
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('value', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('expiration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cache_expiration_index'), ['expiration'], unique=False)

    op.create_table('job_batches',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('total_jobs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_jobs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_job_ids', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('options', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('cancelled_at', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finished_at', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('queue', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('attempts', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('reserved_at', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('available_at', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('jobs_queue_index'), ['queue'], unique=False)

    op.create_table('failed_jobs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('connection', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('queue', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('payload', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('exception', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('failed_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('failed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('failed_jobs_uuid_unique'), ['uuid'], unique=True)

    op.create_table('cache_locks',
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('owner', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('expiration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cache_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('cache_locks_expiration_index'), ['expiration'], unique=False)

    op.drop_table('order_product')
    op.drop_table('cart_product')
    op.drop_table('product_images')
    op.drop_table('orders')
    op.drop_table('carts')
    # ### end Alembic commands ###
