"""empty message

Revision ID: dfb4850ca357
Revises: 5e91e11ce162
Create Date: 2026-07-22 19:37:35.658301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfb4850ca357'
down_revision = '5e91e11ce162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labour')
    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('labour',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('salary', mysql.INTEGER(), server_default=sa.text("'700'"), autoincrement=False, nullable=True),
    sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
