name: Deploy Flask to flask_app

on:
  push:
    branches: [ api ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync to flask_app
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_USERPASSWORD }}
          local-dir: ./
          server-dir: ./flask_app/
          exclude: |
            **/.git**
            **/.github**
            **/venv/**
            **/__pycache__/**
            **/.env

      - name: Restart Passenger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_USERPASSWORD }}
          local-dir: ./tmp/
          server-dir: ./flask_app/tmp/